includedir = src/include
FLAGS := -g 

LIBS = -I$(top_builddir)/$(includedir)/main \
	   -I$(top_builddir)/$(includedir)/master \
	   -I$(top_builddir)/$(includedir)/utils \
	   -I$(top_builddir)/$(includedir)/storage \
	   -I$(top_builddir)/$(includedir)/access

define make_dir 
	cd $1 ; $(MAKE) -f Makefile 
	cd ..
endef


#-I$(top_builddir)/$(includedir) #  ...
